version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sf-backend-prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root123
      - DB_DATABASE=sergio_ferrari
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./images:/app/images
    networks:
      - sf-network-prod

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: runner
    container_name: sf-frontend-prod
    restart: always
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=production
      - PORT=5174
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend
    networks:
      - sf-network-prod

  mysql:
    image: mysql:8.4
    container_name: sf-mysql-prod
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=sergio_ferrari
      - MYSQL_USER=sergio
      - MYSQL_PASSWORD=ferrari123
    volumes:
      - mysql-data-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - sf-network-prod

volumes:
  mysql-data-prod:
    driver: local

networks:
  sf-network-prod:
    driver: bridge
